version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"