openapi: 3.0.0
info:
  title: Entities Links API
  version: v1.0
  description: Entity Links API

servers:
  - url: https://localhost:8081

paths:
  /links/instances/{instanceId}:
    put:
      description: Update links collection related to Instance
      operationId: updateInstanceLinks
      tags:
        - instance-links
      parameters:
        - name: instanceId
          in: path
          required: true
          description: UUID of the Instance that is related to the MARC record
          schema:
            $ref: "#/components/schemas/uuid"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/instanceLinkDtoCollection"
        required: true
      responses:
        "202":
          description: The links were updated
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '422':
          $ref: '#/components/responses/unprocessableEntityResponse'
        '500':
          $ref: '#/components/responses/serverErrorResponse'
    get:
      description: Get links collection related to Instance
      operationId: getInstanceLinks
      tags:
        - instance-links
      parameters:
        - name: instanceId
          in: path
          required: true
          description: UUID of the Instance that is related to the MARC record
          schema:
            $ref: "#/components/schemas/uuid"
      responses:
        "200":
          description: The links collection related to Instance
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/instanceLinkDtoCollection"
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '500':
          $ref: '#/components/responses/serverErrorResponse'

  /links/authorities/bulk/count:
    post:
      description: Retrieve number of links by authority IDs
      operationId: countLinksByAuthorityIds
      tags:
        - instance-links
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/uuidCollection"
        required: true
      responses:
        "200":
          description: The links collection related to Instance
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/linksCountDtoCollection"
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '500':
          $ref: '#/components/responses/serverErrorResponse'

  /linking-rules/instance-authority:
    get:
      description: Retrieve instance-authority linking rules
      operationId: getInstanceAuthorityLinkingRules
      tags:
        - linking-rules
      responses:
        "200":
          description: The authority linking rules collection
          content:
            application/json:
              schema:
                type: array
                title: Collection of linking rules
                description: Collection of linking rules
                items:
                  $ref: '#/components/schemas/linkingRuleDto'
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '500':
          $ref: '#/components/responses/serverErrorResponse'

  /links/authority/stats:
    get:
      description: Retrieve authority updates (related to links) statistics
      operationId: getAuthorityLinksStats
      tags:
        - instance-authority-links-statistics
      parameters:
        - name: fromDate
          in: query
          required: false
          description: Start date to seek from
          schema:
            type: string
            format: date-time
        - name: toDate
          in: query
          required: false
          description: End date to seek from
          schema:
            type: string
            format: date-time
        - name: action
          in: query
          required: false
          description: Action to filter by
          schema:
            $ref: "#/components/schemas/authorityDataStatActionDto"
        - name: limit
          in: query
          required: false
          description: Max number of items in collection
          schema:
            type: integer
            default: 100
      responses:
        "200":
          description: The authority updates statistics collection
          content:
            application/json:
              schema:
                description: Collection of authority updates statistics
                $ref: '#/components/schemas/authorityChangeStatDtoCollection'
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '500':
          $ref: '#/components/responses/serverErrorResponse'

  /links/stats/instance:
    get:
      description: Retrieve linked bib update statistics
      operationId: getLinkedBibUpdateStats
      tags:
        - linked-bib-update-statistics
      parameters:
        - name: fromDate
          in: query
          required: false
          description: Start date to seek from
          schema:
            type: string
            format: date-time
        - name: toDate
          in: query
          required: false
          description: End date to seek to
          schema:
            type: string
            format: date-time
        - name: status
          in: query
          required: false
          description: Status to filter by
          schema:
            $ref: "#/components/schemas/linkStatus"
        - name: limit
          in: query
          required: false
          description: Max number of items in collection
          schema:
            type: integer
            minimum: 1
            default: 99
      responses:
        "200":
          description: The linked bib update statistics collection
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/bibStatsDtoCollection'
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '500':
          $ref: '#/components/responses/serverErrorResponse'

components:
  schemas:
    instanceLinkDtoCollection:
      type: object
      title: Collection of instance links
      description: Collection of instance links
      properties:
        links:
          type: array
          items:
            $ref: '#/components/schemas/instanceLinkDto'
        totalRecords:
          type: integer
          readOnly: true
          description: Total amount of notes
      required:
        - links

    instanceLinkDto:
      type: object
      title: Collection of instance links
      description: Collection of instance links
      properties:
        id:
          type: integer
          description: Unique generated identifier for the link
        authorityId:
          $ref: '#/components/schemas/uuid'
          description: ID of the Authority record
        authorityNaturalId:
          type: string
          description: Natural ID of the Authority record
        instanceId:
          $ref: '#/components/schemas/uuid'
          description: ID of the Instance record
        bibRecordTag:
          type: string
          pattern: '^[0-9]{3}$'
        bibRecordSubfields:
          type: array
          minItems: 1
          maxItems: 100
          items:
            type: string
        linkingRuleId:
          type: integer
          description: ID of linking rule by which link should be created
      required:
        - authorityId
        - authorityNaturalId
        - instanceId
        - bibRecordTag
        - bibRecordSubfields
        - linkingRuleId

    uuidCollection:
      type: object
      title: Collection of UUIDs
      description: Collection of UUIDs
      properties:
        ids:
          type: array
          items:
            $ref: '#/components/schemas/uuid'
      required:
        - ids

    linksCountDtoCollection:
      type: object
      title: Collection of links count map for authorities
      description: Collection of links count map for authorities
      properties:
        links:
          type: array
          items:
            $ref: '#/components/schemas/linksCountDto'
      required:
        - links

    linksCountDto:
      type: object
      title: Total links count map for one authority
      description: Total links count map for one authority
      properties:
        id:
          $ref: '#/components/schemas/uuid'
          description: Authority ID
        totalLinks:
          type: integer
          description: Number of titles linked to the authority

    linkingRuleDto:
      type: object
      title: Field to filed linking rule
      description: Field to filed linking rule
      properties:
        id:
          type: integer
        bibField:
          type: string
        authorityField:
          type: string
        authoritySubfields:
          type: array
          items:
            $ref: '#/components/schemas/charString'
        subfieldModifications:
          type: array
          items:
            $ref: '#/components/schemas/subfieldModification'
        validation:
          $ref: '#/components/schemas/subfieldValidation'

    subfieldModification:
      type: object
      title: Subfield modification.
      description: Subfield modification to link source and target subfields.
      properties:
        source:
          description: Authority subfield.
          $ref: '#/components/schemas/charString'
        target:
          description: Instance subfield.
          $ref: '#/components/schemas/charString'

    subfieldValidation:
      type: object
      title: Subfield validation.
      description: Subfield validation before linking.
      properties:
        existence:
          type: array
          description: Specify if subfield should exist or not.
          items:
            type: string
            additionalProperties:
              type: boolean

    uuid:
      type: string
      format: uuid

    charString:
      type: string
      minLength: 1
      maxLength: 1

    errorResponse:
      type: object
      example:
        Error:
          value:
            errors:
              - message: may not be null
                type: 1
                code: -1
                parameters:
                  - key: moduleTo
                    value: null

    inventoryEvent:
      $ref: schemas/inventoryEvent.json

    inventoryEventType:
      $ref: schemas/inventoryEventType.json

    authorityInventoryRecord:
      $ref: schemas/authorityInventoryRecord.json

    sourceRecord:
      $ref: schemas/sourceRecord.json

    linksChangeEvent:
      type: object
      description: Links change event body
      properties:
        jobId:
          description: Links change job ID
          format: uuid
          type: string
        authorityId:
          description: Authority ID
          format: uuid
          type: string
        type:
          description: Event operation type
          type: string
          enum:
            - UPDATE
            - DELETE
        updateTargets:
          description: MARC Bibs' related instance IDs that are required change grouped by MARC Bib's linked field
          type: array
          items:
            $ref: '#/components/schemas/changeTarget'
        subfieldsChanges:
          description: Subfields to change in MARC bib fields
          type: array
          items:
            $ref: '#/components/schemas/fieldChange'
        tenant:
          description: Tenant id
          type: string
        ts:
          description: Timestamp
          type: string

    changeTarget:
      type: object
      description: MARC Bibs' related instance IDs that are required change and MARC Bib's linked field
      properties:
        field:
          description: MARC Bib's field that required change
          type: string
        links:
          description: Instance-authority links
          items:
            $ref: '#/components/schemas/changeTargetLink'

    changeTargetLink:
      description: Instance-authority target link
      type: object
      properties:
        linkId:
          description: Link ID
          type: integer
          format: int64
        instanceId:
          description: Instance ID
          type: string
          format: uuid

    fieldChange:
      type: object
      description: Change that should be applied to MARC field
      properties:
        field:
          description: MARC bib field
          type: string
        subfields:
          description: MARC bib field's subfield that should be changed
          type: array
          items:
            $ref: '#/components/schemas/subfieldChange'

    subfieldChange:
      type: object
      description: Change that should be applied to MARC subfield
      properties:
        code:
          description: Subfield code
          type: string
        value:
          description: Subfield value. If empty - then remove
          type: string

    authorityDataStatActionDto:
      description: Type of change
      type: string
      enum:
        - DELETE
        - UPDATE_NATURAL_ID
        - UPDATE_HEADING

    authorityDataStatDto:
      type: object
      description: Describe changes to authority that are related to links
      properties:
        id:
          description: Stat ID
          $ref: "#/components/schemas/uuid"
        authorityId:
          description: Authority ID
          $ref: "#/components/schemas/uuid"
        action:
          description: Type of change
          $ref: "#/components/schemas/authorityDataStatActionDto"
        naturalIdOld:
          description: Old natural ID
          type: string
        naturalIdNew:
          description: New natural ID
          type: string
        headingOld:
          description: Old heading
          type: string
        headingNew:
          description: New heading
          type: string
        headingTypeOld:
          description: Old heading type
          type: string
        headingTypeNew:
          description: New heading type
          type: string
        sourceFileOld:
          description: Old source file ID
          type: string
        sourceFileNew:
          description: New source file ID
          type: string
        lbTotal:
          description: Amount of linked bib fields
          type: integer
        lbUpdated:
          description: Amount of linked bib fields that was successfully updated during authority update
          type: integer
        lbFailed:
          description: Amount of linked bib fields that was failed to update during authority update
          type: integer
        metadata:
          description: Statistics metadata
          $ref: '#/components/schemas/metadata'

    authorityChangeStatDtoCollection:
      description: Collection of authority changes statistic
      type: object
      properties:
        stats:
          description: Authority changes statistic
          type: array
          items:
            $ref: "#/components/schemas/authorityDataStatDto"
        next:
          description: Next response item date to seek by
          type: string
          format: date-time

    metadata:
      description: Meta data for authorityDataStatDto
      type: object
      properties:
        startedAt:
          description: Date-time when authority update was registered
          type: string
          format: date-time
        completedAt:
          description: Date-time when update of all related links was completed
          type: string
          format: date-time
        startedByUserId:
          description: User's ID that triggers record
          $ref: "#/components/schemas/uuid"
        startedByUserFirstName:
          description: User's first name that triggers record
          type: string
        startedByUserLastName:
          description: User's last name that triggers record
          type: string

    linkUpdateReport:
      $ref: schemas/linkUpdateReport.json

    linkStatus:
      type: string
      enum:
        - ACTUAL
        - ERROR

    bibStatsDtoCollection:
      description: Collection of linked bibs update statistics
      type: object
      properties:
        stats:
          type: array
          items:
            $ref: schemas/bibStatsDto.json
        next:
          description: Next response item date to seek by
          type: string
          format: date-time

  responses:
    badRequestResponse:
      description: Validation errors.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errorResponse"
    unprocessableEntityResponse:
      description: Validation error for the request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorResponse'
    serverErrorResponse:
      description: Internal server error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorResponse'
