openapi: 3.0.0
info:
  title: Entities Links API
  version: v1.0
  description: Entity Links API

servers:
  - url: https://localhost:8081

paths:
  /links/instances/{instanceId}:
    put:
      description: Update links collection related to Instance
      operationId: updateInstanceLinks
      tags:
        - instance-links
      parameters:
        - name: instanceId
          in: path
          required: true
          description: UUID of the Instance that is related to the MARC record
          schema:
            $ref: "#/components/schemas/uuid"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/instanceLinkDtoCollection"
        required: true
      responses:
        "202":
          description: The links were updated
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '422':
          $ref: '#/components/responses/unprocessableEntityResponse'
        '500':
          $ref: '#/components/responses/serverErrorResponse'
    get:
      description: Get links collection related to Instance
      operationId: getInstanceLinks
      tags:
        - instance-links
      parameters:
        - name: instanceId
          in: path
          required: true
          description: UUID of the Instance that is related to the MARC record
          schema:
            $ref: "#/components/schemas/uuid"
      responses:
        "200":
          description: The links collection related to Instance
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/instanceLinkDtoCollection"
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '500':
          $ref: '#/components/responses/serverErrorResponse'

  /links/authorities/bulk/count:
    post:
      description: Retrieve number of links by authority IDs
      operationId: countLinksByAuthorityIds
      tags:
        - instance-links
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/uuidCollection"
        required: true
      responses:
        "200":
          description: The links collection related to Instance
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/linksCountDtoCollection"
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '500':
          $ref: '#/components/responses/serverErrorResponse'

  /linking-rules/instance-authority:
    get:
      description: Retrieve instance-authority linking rules
      operationId: getInstanceAuthorityLinkingRules
      tags:
        - linking-rules
      responses:
        "200":
          description: The authority linking rules collection
          content:
            application/json:
              schema:
                type: array
                title: Collection of linking rules
                description: Collection of linking rules
                items:
                  $ref: '#/components/schemas/linkingRuleDto'
        '400':
          $ref: '#/components/responses/badRequestResponse'
        '500':
          $ref: '#/components/responses/serverErrorResponse'

components:
  schemas:
    instanceLinkDtoCollection:
      type: object
      title: Collection of instance links
      description: Collection of instance links
      properties:
        links:
          type: array
          items:
            $ref: '#/components/schemas/instanceLinkDto'
        totalRecords:
          type: integer
          readOnly: true
          description: Total amount of notes
      required:
        - links

    instanceLinkDto:
      type: object
      title: Collection of instance links
      description: Collection of instance links
      properties:
        id:
          type: integer
          description: Unique generated identifier for the link
        authorityId:
          $ref: '#/components/schemas/uuid'
          description: ID of the Authority record
        authorityNaturalId:
          type: string
          description: Natural ID of the Authority record
        instanceId:
          $ref: '#/components/schemas/uuid'
          description: ID of the Instance record
        bibRecordTag:
          type: string
          pattern: '^[0-9]{3}$'
        bibRecordSubfields:
          type: array
          minItems: 1
          maxItems: 100
          items:
            type: string
      required:
        - authorityId
        - authorityNaturalId
        - instanceId
        - bibRecordTag
        - bibRecordSubfields

    uuidCollection:
      type: object
      title: Collection of UUIDs
      description: Collection of UUIDs
      properties:
        ids:
          type: array
          items:
            $ref: '#/components/schemas/uuid'
      required:
        - ids

    linksCountDtoCollection:
      type: object
      title: Collection of links count map for authorities
      description: Collection of links count map for authorities
      properties:
        links:
          type: array
          items:
            $ref: '#/components/schemas/linksCountDto'
      required:
        - links

    linksCountDto:
      type: object
      title: Total links count map for one authority
      description: Total links count map for one authority
      properties:
        id:
          $ref: '#/components/schemas/uuid'
          description: Authority ID
        totalLinks:
          type: integer
          format: int64
          description: Number of titles linked to the authority

    linkingRuleDto:
      type: object
      title: Field to filed linking rule
      description: Field to filed linking rule
      properties:
        bibField:
          type: string
        authorityField:
          type: string
        authoritySubfields:
          type: array
          items:
            $ref: '#/components/schemas/charString'
        subfieldModifications:
          type: array
          items:
            $ref: '#/components/schemas/subfieldModification'
        validation:
          $ref: '#/components/schemas/subfieldValidation'

    subfieldModification:
      type: object
      title: Subfield modification.
      description: Subfield modification to link source and target subfields.
      properties:
        source:
          description: Authority subfield.
          $ref: '#/components/schemas/charString'
        target:
          description: Instance subfield.
          $ref: '#/components/schemas/charString'

    subfieldValidation:
      type: object
      title: Subfield validation.
      description: Subfield validation before linking.
      properties:
        existence:
          type: array
          description: Specify if subfield should exist or not.
          items:
            type: string
            additionalProperties:
              type: boolean

    uuid:
      type: string
      format: uuid

    charString:
      type: string
      minLength: 1
      maxLength: 1

    errorResponse:
      type: object
      example:
        Error:
          value:
            errors:
              - message: may not be null
                type: 1
                code: -1
                parameters:
                  - key: moduleTo
                    value: null

    inventoryEvent:
      $ref: schemas/inventoryEvent.json

    inventoryEventType:
      $ref: schemas/inventoryEventType.json

    authorityInventoryRecord:
      $ref: schemas/authorityInventoryRecord.json

    sourceRecord:
      $ref: schemas/sourceRecord.json

    linksChangeEvent:
      type: object
      description: Links change event body
      properties:
        jobId:
          description: Links change job ID
          format: uuid
          type: string
        authorityId:
          description: Authority ID
          format: uuid
          type: string
        type:
          description: Event operation type
          type: string
          enum:
            - UPDATE
            - DELETE
        updateTargets:
          description: MARC Bibs' related instance IDs that are required change grouped by MARC Bib's linked field
          type: array
          items:
            $ref: '#/components/schemas/changeTarget'
        subfieldsChanges:
          description: Subfields to change in MARC bib fields
          type: array
          items:
            $ref: '#/components/schemas/fieldChange'
        tenant:
          description: Tenant id
          type: string
        ts:
          description: Timestamp
          type: string

    changeTarget:
      type: object
      description: MARC Bibs' related instance IDs that are required change and MARC Bib's linked field
      properties:
        field:
          description: MARC Bib's field that required change
          type: string
        instanceIds:
          description: Instance IDs
          type: array
          items:
            format: uuid
            type: string

    fieldChange:
      type: object
      description: Change that should be applied to MARC field
      properties:
        field:
          description: MARC bib field
          type: string
        subfields:
          description: MARC bib field's subfield that should be changed
          type: array
          items:
            $ref: '#/components/schemas/subfieldChange'

    subfieldChange:
      type: object
      description: Change that should be applied to MARC subfield
      properties:
        code:
          description: Subfield code
          type: string
        value:
          description: Subfield value. If empty - then remove
          type: string

  responses:
    badRequestResponse:
      description: Validation errors.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errorResponse"
    unprocessableEntityResponse:
      description: Validation error for the request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorResponse'
    serverErrorResponse:
      description: Internal server error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorResponse'
